### ISSUE TITLE
My GPU utilization is dropping down to 0 % every 5-10min

### ISSUE THREAD

**Issue by MrPalmie** [FR33THYFR33THY/Ultimate-Windows-Optimization-Guide#2]
I have the problem that my GPU utilization in games like Fortnite goes down to 0 percent every 5 minutes. The voltage, processor clock and memory speed remain constant at 1.050 V, 2055 MHz and 7900 MHz. 

GPU: Nvidia Geforce RTX 3070 Gainward Phoenix GS V1 (OC Stable)

CPU: AMD Ryzen 9 3900X (PBO Stable)

RAM: 4x 16gb Corsair Vengeance RGB RT 3600 mhz cl16

Mainboard: B550 Aorus Elite V2

I have the latest graphics card driver (565.90 of course the game driver) and the latest chipset drivers.

I always have my graphics card fans set to almost maximum. So you can rule out the possibility of it clocking down due to too high temperature.

I have installed two different Windows 10 systems with dual boot because I also make music on the side and don't want to mix things up. Both systems are on the same Kingston SSD and separated by partitions.

Things I have already tried:

Reinstall Windows 10 with the Windows Optimization Guide.

2 Ram bars instead of 4.

Lowered the ram speed to 3200 Mhz.

Command Rate from 1T and Gear Down Mode On to Command Rate 2T and GDM Off. 

Disable Powerdown mode. 

Removed the graphics drivers with DDU and installed once with NVCleaninstall and once without. 

Hope someone can help me.

**Comment by MrPalmie** [comment]
![Unbenannt](https://github.com/user-attachments/assets/1908d4aa-91a6-4870-82fa-9bcd7cd4932d)
Thats a screenshot I did after the Problem occurred

**Comment by FR33THYFR33THY** [comment]
it's some kind of hardware issue
you would need gear down mode on with 4 sticks in that board

i would upgrade to a 5800x3d tbh
and as far as your issue, could be anything hardware related
or ram instability. does the game drop frames with default bios settings and docp on

**Comment by MrPalmie** [comment]
Thanks for your quick reply👍. I will test it with BIOS defaults. 

Before I had GDM Enabled and was running the command rate on T1. Why should I switch it on when running T2 when it works both ways?

**Comment by MrPalmie** [comment]
Thanks for your quick reply👍. I will test it with BIOS defaults. 

Before I had GDM Enabled and was running the command rate on T1. Why should I switch it on when running T2 when it works both ways? 

I don't have any kind of performance loss on my Music (non optimized Windows10) with the same BIOS settings in Games like Jedi Fallen Order, Jedi Survivor, The Last of Us and Assetto Corsa Competizione

**Comment by MrPalmie** [comment]
Tried BIOS Settings Default. One time with docp off and one time on. 

I'm pretty sure that the issue is because of the tweaked windows. Maybe some of the GPU settings done in the Registry?

**Comment by MrPalmie** [comment]
Because I have had the PC since 2021. I only bought two new ram sticks exactly the same as my old two ones and I never had issues before it and not shortly after it. And as I said, all the other games on my Music (non optimized W10) work perfectly fine without issues.

**Comment by FR33THYFR33THY** [comment]
if there is an issue with your hardware/pc optimizing will just make the issue worse.
there is something wrong with your hardware/pc.
