### ISSUE TITLE
Why My System Only Has the Balanced Power Plan: How to Unlock High Performance and Ultimate Performance Modes in Windows

### ISSUE THREAD

**Issue by AayushV12** [FR33THYFR33THY/Ultimate-Windows-Optimization-Guide#3]
My Asus ROG Strix G15 2022 laptop is powered by an AMD Ryzen™ 7 6800H processor, an 8-core, 16-thread CPU capable of reaching clock speeds up to 4.7 GHz. Paired with 16GB of DDR5 RAM (dual-channel) and an NVIDIA® GeForce RTX™ 3050 (4GB GDDR6) GPU, it’s designed for high-performance gaming and multitasking. Despite this powerful hardware, the system is restricted to the Balanced power plan, limiting its full potential. By unlocking the High Performance or even Ultimate Performance modes through tweaks or overrides,can 
 i push my laptop's connected to power all the time's CPU and GPU to deliver maximum power for intensive gaming and creative tasks. Or should i let it remain on balanced plan . which will u reccomend

**Comment by gameshler** [comment]
Laptops are not designed as desktop pc's performance however i have used a similar laptop on the ultimate performance power plan while also connected to the power it definitely improved my fps a lot and my overall gaming experience. 

if you are talking over the long run,  nothing happened to my laptop  and i used to game like 8 hours straight. 

The choice is yours whether to stay on balanced or ultimate performance power plan but i would recommend going for the ultimate performance as you would maximize your laptop's potential.

**Comment by FR33THYFR33THY** [comment]
if you always keep your laptop plugged in, just use the ultimate power plan.
although, power plan doesn't matter on amd cpus
