### ISSUE TITLE
Sound.ps1 issue

### ISSUE THREAD

**Issue by xXMrPotatoXx** [FR33THYFR33THY/Ultimate-Windows-Optimization-Guide#5]
Hey, i just used your Sound.ps1 file and it said if i want to enable sound EQ i clicked yes and then it asked me to write the name of the speaker because it didnt found it. I typed speaker then a window popped up to give powershell administrator privileges and then it closed. When i checked it didnt turn on Sound EQ. I tried 3 times but nothing. Maybe the problem is with my pc i dont know. What does it exactly do? Is it a problem if I ran it 3 times?

it say this:
cmdlet EQ.ps1 at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
PlaybackDeviceName:

When i type speaker it opens another powershell and then it closes with some red text showing which i cant read.

i can see that it is messing with registry:
&regFile = "&env:temp\SoundEnhancementsTMP.reg"
&enhancementFlagKey = "{fc52a749-4be9-4510-896e-966ba6525980},3"
&releaseTimeKey = "{9c00eeed-edce-4cd8-ae08-cb05e8ef57a0},3"
&enhancementTabKey = "{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},3"
&enhancementTabValue = "{5860E1C5-F95C-4a7a-8EC8-8AEF24F379A1}"
&releaseTimeStr = &releaseTime.ToString().PadLeft(2,'0')
&fxPropertiesImport = @'
"{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},1"="{62dc1a93-ae24-464c-a43e-452f824c4250}" ;PreMixEffectClsid activates effects
"{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},2"="{637c490d-eee3-4c0a-973f-371958802da2}" ;PostMixEffectClsid activates effects
"{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},3"="{5860E1C5-F95C-4a7a-8EC8-8AEF24F379A1}" ;UserInterfaceClsid shows it in ui
"{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},5"="{62dc1a93-ae24-464c-a43e-452f824c4250}" ;StreamEffectClsid
"{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},6"="{637c490d-eee3-4c0a-973f-371958802da2}" ;ModeEffectClsid
"{fc52a749-4be9-4510-896e-966ba6525980},3"=hex:0b,00,00,00,01,00,00,00,ff,ff,00,00 ;enables loudness equalisation
"{9c00eeed-edce-4cd8-ae08-cb05e8ef57a0},3"=hex:03,00,01,60,01,00,00,00,02,00,00,00 ;equalisation release time max

what does it do and if it does anything to the registry then add an option to reverb it.

**Comment by gameshler** [comment]
When you run the script it opens up a sound control panel that has all your playback devices which contains the name of each device copy it then continue with the script if the panel closes you can open it up from the sound settings or you can run this command in your PowerShell as administrator; it lists the Names & Id's of every audio device in your pc then just copy the name and past it then it will automatically enable Loudness EQ

```sh
Get-CimInstance win32_sounddevice | Select-Object Name, DeviceID | Sort-Object Name

```

**Comment by FR33THYFR33THY** [comment]
doesnt work on some sound cards with w11
if thats the case if you uninstall the sound card drivers, you should be able to get it to work with the generic sound drivers on w11
although you wont be able to use 7.1 without the drivers

w10 doesnt have this issue
